### ISSUE TITLE
Compose box missing on canary

### ISSUE THREAD

**Issue by llimllib** [elk-zone/elk#1530]
Connecting to my account at https://vis.social with either my own copy of canary or your copy, I can log in but I do not get a compose box at the top of the page. 

If I click on the compose element on the sidebar, I get a blank page.

The page does load toots normally as they come in.

Reproducible on firefox and on safari.

Here's the console.log output from safari:

```
[Error] TypeError: undefined is not an object (evaluating 't.status')
<snip unhelpful traceback>
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (subscription, line 0) https://vis.social/api/v1/push/subscription
[Error] Origin https://elk.pwm.social is not allowed by Access-Control-Allow-Origin. Status code: 200
[Error] Fetch API cannot load https://vis.social/nodeinfo/2.0 due to access control checks.
[Error] Failed to load resource: Origin https://elk.pwm.social is not allowed by Access-Control-Allow-Origin. Status code: 200 (2.0, line 0) https://vis.social/nodeinfo/2.0
[Error] TypeError: undefined is not an object (evaluating 'l.value.params.status')
<snip>
```

If I go to your main instance at elk.zone, the compose box is still present.

Is this due to an error with the mastodon server I connect to? If so maybe it could be solved with a user-facing error message of some sort? How could I debug that?

In the server's log, I get these errors:

<details>
<summary>elk log output</summary>

```
[Vue warn]: Unhandled error during execution of async component loader
  at <AsyncComponentWrapper error= H3Error: Page Not Found: /_nuxt/_...permalink_.05142f2a.js
    at createError (file:///Users/llimllib/code/elk/.output/server/node_modules/h3/dist/index.mjs:125:15)
    at file:///Users/llimllib/code/elk/.output/server/chunks/app/server.mjs:4968:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 404,
  fatal: false,
  unhandled: false,
  statusMessage: 'Page Not Found: /_nuxt/_...permalink_.05142f2a.js',
  __nuxt_error: true
} >
[Vue warn]: Unhandled error during execution of setup function
  at <AsyncComponentWrapper error= H3Error: Page Not Found: /_nuxt/_...permalink_.05142f2a.js
    at createError (file:///Users/llimllib/code/elk/.output/server/node_modules/h3/dist/index.mjs:125:15)
    at file:///Users/llimllib/code/elk/.output/server/chunks/app/server.mjs:4968:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  statusCode: 404,
  fatal: false,
  unhandled: false,
  statusMessage: 'Page Not Found: /_nuxt/_...permalink_.05142f2a.js',
  __nuxt_error: true
} >
[Vue warn]: Unhandled error during execution of async component loader
  at <AsyncComponentWrapper error= {
  url: '/_nuxt/_...permalink_.05142f2a.js',
  statusCode: '404',
  statusMessage: 'Page Not Found: /_nuxt/_...permalink_.05142f2a.js',
  message: 'Page Not Found: /_nuxt/_...permalink_.05142f2a.js',
  stack: ''
} >
[Vue warn]: Unhandled error during execution of setup function
  at <AsyncComponentWrapper error= {
  url: '/_nuxt/_...permalink_.05142f2a.js',
  statusCode: '404',
  statusMessage: 'Page Not Found: /_nuxt/_...permalink_.05142f2a.js',
  message: 'Page Not Found: /_nuxt/_...permalink_.05142f2a.js',
  stack: ''
} >
[nuxt] [request error] [unhandled] [500] Cannot find module '/Users/llimllib/code/elk/.output/server/chunks/app/_nuxt/error-component.8d67a9df.mjs' imported from /Users/llimllib/code/elk/.output/server/chunks/app/server.mjs
  at new NodeError (node:internal/errors:399:5)
  at finalizeResolution (node:internal/modules/esm/resolve:231:11)
  at moduleResolve (node:internal/modules/esm/resolve:850:10)
  at defaultResolve (node:internal/modules/esm/resolve:1058:11)
  at nextResolve (node:internal/modules/esm/loader:164:28)
  at ESMLoader.resolve (node:internal/modules/esm/loader:838:30)
  at ESMLoader.getModuleJob (node:internal/modules/esm/loader:419:18)
  at ESMLoader.import (node:internal/modules/esm/loader:520:22)
  at importModuleDynamically (node:internal/modules/esm/translators:108:35)
  at importModuleDynamicallyCallback (node:internal/modules/esm/utils:85:14)
```

</details>

**Comment by boehs** [comment]
possibly related #1472

**Comment by llimllib** [comment]
Not quite sure what changed, but the compose box is back after I updated to [611b6be](https://github.com/elk-zone/elk/commit/611b6bece70bb53c2ee73d4777d02d35c4734653)
