### ISSUE TITLE
Cannot compose new posts and replies.

### ISSUE THREAD

**Issue by kovalBlazej** [elk-zone/elk#2273]
For last few days, there is the empty page when I click 'compose', and also no input when trying to reply in a thread. Same issue on Chromium and Firefox. My instance is pol.social and it runs Mastodon 4.1.5.
After clicking 'compose' there is an error in the console
```
SyntaxError: 15 (at entry.95bc1761.js:23:511)
    at O_ (entry.95bc1761.js:23:511)
    at Gt (entry.95bc1761.js:35:642)
    at fe (entry.95bc1761.js:35:4448)
    at me (entry.95bc1761.js:35:4505)
    at setup (PublishWidget.76c81b8d.js:92:9903)
    at nr (entry.95bc1761.js:1:13825)
    at iE (entry.95bc1761.js:1:63917)
    at sE (entry.95bc1761.js:1:63702)
    at U (entry.95bc1761.js:1:51031)
    at M (entry.95bc1761.js:1:50924)
nw @ entry.95bc1761.js:1
zo @ entry.95bc1761.js:1
nr @ entry.95bc1761.js:1
iE @ entry.95bc1761.js:1
sE @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
M @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
F @ entry.95bc1761.js:1
T @ entry.95bc1761.js:1
b @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
M @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
Ot @ entry.95bc1761.js:1
me @ entry.95bc1761.js:1
P @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
L @ entry.95bc1761.js:1
R @ entry.95bc1761.js:1
b @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
nr @ entry.95bc1761.js:1
by @ entry.95bc1761.js:1
Promise.then (async)
Dy @ entry.95bc1761.js:1
kl @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
yp @ entry.95bc1761.js:1
du @ entry.95bc1761.js:1
Gf @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
yp @ entry.95bc1761.js:1
du @ entry.95bc1761.js:1
Gf @ entry.95bc1761.js:1
set value @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:39
o @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
app:suspense:resolve (async)
PF @ entry.95bc1761.js:1
callHookWith @ entry.95bc1761.js:1
callHook @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
Promise.finally (async)
(anonymous) @ entry.95bc1761.js:52
Promise.then (async)
lt @ entry.95bc1761.js:1
onResolve @ entry.95bc1761.js:52
Ei @ entry.95bc1761.js:1
resolve @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
Promise.then (async)
registerDep @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
p @ entry.95bc1761.js:1
d @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
yw @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
p @ entry.95bc1761.js:1
h @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
p @ entry.95bc1761.js:1
d @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
p @ entry.95bc1761.js:1
d @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
p @ entry.95bc1761.js:1
d @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
p @ entry.95bc1761.js:1
d @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
Promise.then (async)
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
Promise.then (async)
registerDep @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
yw @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
p @ entry.95bc1761.js:1
h @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
yw @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
Ue @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
f @ entry.95bc1761.js:1
u @ entry.95bc1761.js:1
mount @ entry.95bc1761.js:1
ME.t.mount @ entry.95bc1761.js:1
Gg @ entry.95bc1761.js:55
await in Gg (async)
(anonymous) @ entry.95bc1761.js:55
entry.95bc1761.js:1 SyntaxError: 15 (at entry.95bc1761.js:23:511)
    at O_ (entry.95bc1761.js:23:511)
    at Gt (entry.95bc1761.js:35:642)
    at fe (entry.95bc1761.js:35:4448)
    at me (entry.95bc1761.js:35:4505)
    at setup (PublishWidget.76c81b8d.js:92:9903)
    at nr (entry.95bc1761.js:1:13825)
    at iE (entry.95bc1761.js:1:63917)
    at sE (entry.95bc1761.js:1:63702)
    at U (entry.95bc1761.js:1:51031)
    at M (entry.95bc1761.js:1:50924)
nw @ entry.95bc1761.js:1
zo @ entry.95bc1761.js:1
nr @ entry.95bc1761.js:1
iE @ entry.95bc1761.js:1
sE @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
M @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
F @ entry.95bc1761.js:1
T @ entry.95bc1761.js:1
b @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
F @ entry.95bc1761.js:1
T @ entry.95bc1761.js:1
b @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
nr @ entry.95bc1761.js:1
by @ entry.95bc1761.js:1
by @ entry.95bc1761.js:1
Promise.then (async)
Dy @ entry.95bc1761.js:1
_y @ entry.95bc1761.js:1
Fy @ entry.95bc1761.js:1
r.deactivate @ entry.95bc1761.js:1
tt @ entry.95bc1761.js:1
resolve @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
Promise.then (async)
registerDep @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
M @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
M @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
X @ entry.95bc1761.js:1
U @ entry.95bc1761.js:1
M @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
gw @ entry.95bc1761.js:1
process @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
re @ entry.95bc1761.js:1
M @ entry.95bc1761.js:1
m @ entry.95bc1761.js:1
V @ entry.95bc1761.js:1
run @ entry.95bc1761.js:1
X.w.update @ entry.95bc1761.js:1
nr @ entry.95bc1761.js:1
by @ entry.95bc1761.js:1
Promise.then (async)
Dy @ entry.95bc1761.js:1
kl @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
yp @ entry.95bc1761.js:1
du @ entry.95bc1761.js:1
Gf @ entry.95bc1761.js:1
(anonymous) @ entry.95bc1761.js:1
yp @ entry.95bc1761.js:1
du @ entry.95bc1761.js:1
Gf @ entry.95bc1761.js:1
set value @ entry.95bc1761.js:1
P @ entry.95bc1761.js:5
(anonymous) @ entry.95bc1761.js:5
Promise.then (async)
x @ entry.95bc1761.js:5
D @ entry.95bc1761.js:5
a @ entry.95bc1761.js:5
(anonymous) @ entry.95bc1761.js:1
nr @ entry.95bc1761.js:1
zt @ entry.95bc1761.js:1
zt @ entry.95bc1761.js:1
n @ entry.95bc1761.js:1
```
![obraz](https://github.com/elk-zone/elk/assets/32499600/3b3cbfe6-1a75-4d25-a929-5a73b00f1dac)

**Comment by hrw** [comment]
Confirming.

Firefox 115

**Comment by kovalBlazej** [comment]
I mitigated the issue by switching the language to English.

**Comment by widersky** [comment]
Looks like this issue occurs on Safari too

**Comment by userquin** [comment]
Refreshing the page, I'll try to debug in my local what's the error:

![imagen](https://github.com/elk-zone/elk/assets/6311119/ce8a1fc7-0060-4f5b-a7bf-6f28e91f5c8d)
