### ISSUE TITLE
Unhelpful build/documentation error "/public/pinned not found"

### ISSUE THREAD

**Issue by snail-coupe** [elk-zone/elk#2476]
I'm trying to build to run in IONOS's deploy noe stateless server environment, but the build keeps failing with:

```
Errors prerendering:
[log] [nitro]   ├─ /public/pinned (228ms)
  │ ├── Error: [404] Page Not Found: /public/pinned
  │ └── Linked from /pinned
[log] [nitro]
Error:  Exiting due to prerender errors.
  at prerender (node_modules/.pnpm/nitropack@2.6.3_idb-keyval@6.2.1/node_modules/nitropack/dist/shared/nitro.d72ac66e.mjs:212:11)
  at async node_modules/.pnpm/nuxt@3.7.4_eslint@8.49.0_idb-keyval@6.2.1_rollup@2.79.1_typescript@5.1.6_vue-tsc@1.8.8/node_modules/nuxt/dist/index.mjs:2943:7
  at async build (node_modules/.pnpm/nuxt@3.7.4_eslint@8.49.0_idb-keyval@6.2.1_rollup@2.79.1_typescript@5.1.6_vue-tsc@1.8.8/node_modules/nuxt/dist/index.mjs:4315:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.9.0/node_modules/nuxi/dist/chunks/build.mjs:92:5)
  at async Object.run (node_modules/.pnpm/nuxi@3.9.0/node_modules/nuxi/dist/chunks/generate.mjs:61:5)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.9.0/node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1647:7)
  at async runCommand$1 (node_modules/.pnpm/nuxi@3.9.0/node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1638:11)
  at async runMain$1 (node_modules/.pnpm/nuxi@3.9.0/node_modules/nuxi/dist/shared/nuxi.9d864d83.mjs:1770:7) 

Error:  Exiting due to prerender errors.
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.

```

This is a fork off 0.10.3 - obviously it builds for others, but I can't work out what I'm missing or find any mention of having to do anything specific in the docs?

Just a thought, are there minimum versions for the various stack components?  (Originally it had defaulted to node 15!)

**Comment by alexzhang1030** [comment]
Have you been able to test the latest code? Looks like it's not a normal error.

**Comment by snail-coupe** [comment]
latest as in main? I haven't but will give it a go

**Comment by snail-coupe** [comment]
pulling in main just now and same error,  I let Ionos add there standard workflows so I don't know what it is doing under the hood, but I'm assuming it must be roughly right as getting a good way through the build it feels,
