### ISSUE TITLE
User profile panel is not shown when hovering

### ISSUE THREAD

**Issue by shuuji3** [elk-zone/elk#2601]
Tested version: Canary (https://github.com/elk-zone/elk/commit/b9394c2fa54d3899dd79bcc808cfc2af4245c144)

When hovering on the `@username` link, it doesn't show the profile panel but console log the following error:

![Screenshot from 2024-02-22 00-12-27](https://github.com/elk-zone/elk/assets/1425259/c962961a-c68a-44b7-b7fc-52590c1fa7e3)

```js
entry.1f2092ce.js:1 TypeError: Cannot read properties of undefined (reading 'includes')
    at Fa (entry.1f2092ce.js:8:13373)
    at sl (entry.1f2092ce.js:8:13539)
    at qs (entry.1f2092ce.js:8:13749)
    at Proxy.<anonymous> (entry.1f2092ce.js:52:16681)
    at vl (entry.1f2092ce.js:1:17142)
    at wu.z [as fn] (entry.1f2092ce.js:1:52929)
    at wu.run (entry.1f2092ce.js:1:4872)
    at U.b.update (entry.1f2092ce.js:1:53208)
    at U (entry.1f2092ce.js:1:53234)
    at ee (entry.1f2092ce.js:1:52047)
```

**Comment by shuuji3** [comment]
`<AccountHoverCard>`'s `account` prop expects a value of `mastodon.v1.Account`.

However, the current type is `ComputedRef<mastodon.v1.Account | Ref<mastodon.v1.Account | null> | undefined >` here: https://github.com/elk-zone/elk/blob/main/components/account/AccountHoverWrapper.vue#L14

This wrong typed value is being passed into `getFullHandle()` and `account.acct` become `undefined` at the end here: https://github.com/elk-zone/elk/blob/8d792d003ddad681e7b2f680d30a0128561ebd46/composables/masto/account.ts#L29

**Comment by shuuji3** [comment]
This issue had already fixed in the Canary version.
