### ISSUE TITLE
Fix errors during test script

### ISSUE THREAD

**Issue by shuuji3** [elk-zone/elk#2934]
Although all tests seem to pass, a few errors during the test run look related to the WPA manifest file.

Here's the GitHub Actions log from `pnpm test:ci` command:

[chore(deps): update devdependencies · elk-zone/elk@e1a5d83](https://github.com/elk-zone/elk/actions/runs/10570912138/job/29286149498?pr=2931)

```shell
Run pnpm test:ci

> @elk-zone/elk@0.1[4](https://github.com/elk-zone/elk/actions/runs/10570912138/job/29286149498?pr=2931#step:7:5).0 test:ci /home/runner/work/elk/elk
> nr test:unit:ci


> @elk-zone/elk@0.14.0 test:unit:ci /home/runner/work/elk/elk
> stale-dep && vitest run

Using `2024-04-03` as fallback compatibility date.
[nuxt] Expected `@nuxt/schema` to be at least `3.13.0` but got `3.12.4`. This might lead to unexpected behavior. Check your package.json or refresh your lockfile.
[nuxt] Expected `@nuxt/kit` to be at least `3.13.0` but got `3.12.4`. This might lead to unexpected behavior. Check your package.json or refresh your lockfile.

 RUN  v2.0.[5](https://github.com/elk-zone/elk/actions/runs/10570912138/job/29286149498?pr=2931#step:7:6) /home/runner/work/elk/elk

stdout | tests/nuxt/html-to-text.test.ts
<Suspense> is an experimental feature and its API will likely change.

stderr | tests/nuxt/html-to-text.test.ts
[nuxt] Error fetching app manifest. FetchError: [GET] "/_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json": 404 Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at $fetch2 (file:///home/runner/work/elk/elk/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.3738[6](https://github.com/elk-zone/elk/actions/runs/10570912138/job/29286149498?pr=2931#step:7:7)b05.mjs:268:15)
[nuxt] error caught during app initialization FetchError: [GET] "/_nuxt/builds/meta/dcdd3[7](https://github.com/elk-zone/elk/actions/runs/10570912138/job/29286149498?pr=2931#step:7:8)[8](https://github.com/elk-zone/elk/actions/runs/10570912138/job/29286149498?pr=2931#step:7:9)e-543d-4c83-888d-c0fec58dacf2.json": 404 Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.
    at processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/elk-zone/elk/actions/runs/10570912138/job/29286149498?pr=2931#step:7:10)5:5)
    at $fetch2 (file:///home/runner/work/elk/elk/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15) {
  cause: FetchError: [GET] "/_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json": 404 Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at $fetch2 (file:///home/runner/work/elk/elk/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15),
  statusCode: 404,
  fatal: false,
  unhandled: false,
  statusMessage: 'Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.',
  data: {
    statusCode: 404,
    statusMessage: 'Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.',
    stack: []
  }
}

stdout | tests/nuxt/content-rich.test.ts
stderr | tests/nuxt/content-rich.test.ts
[nuxt] Error fetching app manifest. FetchError: [GET] "/_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json": 404 Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at $fetch2 (file:///home/runner/work/elk/elk/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15)
[nuxt] error caught during app initialization FetchError: [GET] "/_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json": 404 Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at $fetch2 (file:///home/runner/work/elk/elk/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15) {
  cause: FetchError: [GET] "/_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json": 404 Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at $fetch2 (file:///home/runner/work/elk/elk/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15),
  statusCode: 404,
  fatal: false,
  unhandled: false,
  statusMessage: 'Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.',
  data: {
    statusCode: 404,
    statusMessage: 'Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.',
    stack: []
  }
}
<Suspense> is an experimental feature and its API will likely change.

stderr | tests/nuxt/html-parse.test.ts
[nuxt] Error fetching app manifest. FetchError: [GET] "/_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json": 404 Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at $fetch2 (file:///home/runner/work/elk/elk/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15)
[nuxt] error caught during app initialization FetchError: [GET] "/_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json": 404 Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at $fetch2 (file:///home/runner/work/elk/elk/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15) {
  cause: FetchError: [GET] "/_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json": 404 Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at $fetch2 (file:///home/runner/work/elk/elk/node_modules/.pnpm/ofetch@1.3.4/node_modules/ofetch/dist/shared/ofetch.37386b05.mjs:268:15),
  statusCode: 404,
  fatal: false,
  unhandled: false,
  statusMessage: 'Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.',
  data: {
    statusCode: 404,
    statusMessage: 'Cannot find any path matching /_nuxt/builds/meta/dcdd378e-543d-4c83-888d-c0fec58dacf2.json.',
    stack: []
  }
}


stdout | tests/nuxt/html-parse.test.ts
<Suspense> is an experimental feature and its API will likely change.

 ✓ tests/nuxt/html-to-text.test.ts  (3 tests) 5ms
 ✓ tests/nuxt/html-parse.test.ts  (8 tests) 98ms
[@vue/compiler-sfc] This project is using reactive props destructure, which is an experimental feature. It may receive breaking changes or be removed in the future, so use at your own risk.
To stay updated, follow the RFC at https://github.com/vuejs/rfcs/discussions/502.

 ✓ tests/unit/language.test.ts  (1 test) 7ms
 ✓ tests/unit/permalinks.test.ts  (6 tests) 5ms
 ✓ tests/unit/reorder-timeline.test.ts  (2 tests) 4ms
stderr | tests/nuxt/content-rich.test.ts > content-rich > hashtag adds bdi
[Vue warn]: Failed to resolve component: VMenu
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

stderr | tests/nuxt/content-rich.test.ts > content-rich > hashtag doesn't add 2 bdi
[Vue warn]: Failed to resolve component: VMenu
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

stderr | tests/nuxt/content-rich.test.ts > content-rich > root p includes dir="auto" attr when mixed content
[Vue warn]: Failed to resolve component: VMenu
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: VMenu
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: VMenu
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.
[Vue warn]: Failed to resolve component: VMenu
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement.

 ✓ tests/nuxt/content-rich.test.ts  (25 tests) 140ms

 Test Files  6 passed (6)
      Tests  45 passed (45)
   Start at  03:00:49
   Duration  5.31s (transform 3.97s, setup 8.42s, collect 2.65s, tests 259ms, environment 1.[11](https://github.com/elk-zone/elk/actions/runs/10570912138/job/29286149498?pr=2931#step:7:12)s, prepare 1.16s)
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by fvsch** [comment]
I can fix the `[Vue warn]: Failed to resolve component: VMenu` by using the component that I suspect this is using implicitly:
https://floating-vue.starpad.dev/guide/component#hover-menu

The component is exported as `Menu` from `floating-vue`, but is supposed to be registered as `VMenu` when defining the Nuxt plugin. Dunno why that's not picked up by Vitest or by intellisense though.

A possible fix is implicitly importing the component before using it:

```ts
import { Menu as VMenu } from 'floating-vue'
```

This fixes the warnings, but then it changes the test snapshots by actually calling the component's logic instead of treating it as a custom HTML tag.
