### ISSUE TITLE
weird error when logout

### ISSUE THREAD

**Issue by userquin** [elk-zone/elk#395]
Sometimes when logout from the app, there is an error on `floating-vue` (the entries not loaded):

<details>
<summary>Error</summary>

```shell
floating-vue.es.js:980 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getBoundingClientRect')
    at Proxy.$_isAimingPopper (floating-vue.es.js:980:52)
    at Proxy.hide (floating-vue.es.js:526:50)
    at Proxy.deactivated (floating-vue.es.js:494:10)
    at hook.__wdc.hook.__wdc (runtime-core.esm-bundler.js:2660:20)
    at callWithErrorHandling (runtime-core.esm-bundler.js:157:22)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:166:21)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:2713:29)
    at invokeArrayFns (shared.esm-bundler.js:552:13)
    at Array.<anonymous> (runtime-core.esm-bundler.js:2477:21)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:343:32)
$_isAimingPopper @ floating-vue.es.js:980
hide @ floating-vue.es.js:526
deactivated @ floating-vue.es.js:494
hook.__wdc.hook.__wdc @ runtime-core.esm-bundler.js:2660
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
hook.__weh.hook.__weh @ runtime-core.esm-bundler.js:2713
invokeArrayFns @ shared.esm-bundler.js:552
(anonymous) @ runtime-core.esm-bundler.js:2477
flushPostFlushCbs @ runtime-core.esm-bundler.js:343
flushJobs @ runtime-core.esm-bundler.js:397
await in flushJobs (async)
watch.immediate @ paginator.ts:54
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
job @ runtime-core.esm-bundler.js:1794
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
scheduler @ runtime-core.esm-bundler.js:1827
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
triggerRefValue @ reactivity.esm-bundler.js:1003
(anonymous) @ reactivity.esm-bundler.js:1137
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:1003
set value @ reactivity.esm-bundler.js:1048
update @ index.mjs?v=1ed314f6:1978
loadNext @ paginator.ts:45
await in loadNext (async)
watch.immediate @ paginator.ts:54
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
job @ runtime-core.esm-bundler.js:1794
doWatch @ runtime-core.esm-bundler.js:1837
watch @ runtime-core.esm-bundler.js:1671
usePaginator @ paginator.ts:50
setup @ CommonPaginator.vue:20
callWithErrorHandling @ runtime-core.esm-bundler.js:157
setupStatefulComponent @ runtime-core.esm-bundler.js:7246
setupComponent @ runtime-core.esm-bundler.js:7201
mountComponent @ runtime-core.esm-bundler.js:5524
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
processFragment @ runtime-core.esm-bundler.js:5458
patch @ runtime-core.esm-bundler.js:5094
mountChildren @ runtime-core.esm-bundler.js:5285
processFragment @ runtime-core.esm-bundler.js:5458
patch @ runtime-core.esm-bundler.js:5094
mountChildren @ runtime-core.esm-bundler.js:5285
mountElement @ runtime-core.esm-bundler.js:5195
processElement @ runtime-core.esm-bundler.js:5178
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
(anonymous) @ runtime-core.esm-bundler.js:1487
Promise.then (async)
registerDep @ runtime-core.esm-bundler.js:1466
mountComponent @ runtime-core.esm-bundler.js:5532
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountSuspense @ runtime-core.esm-bundler.js:1209
process @ runtime-core.esm-bundler.js:1185
patch @ runtime-core.esm-bundler.js:5107
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
processFragment @ runtime-core.esm-bundler.js:5458
patch @ runtime-core.esm-bundler.js:5094
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
processFragment @ runtime-core.esm-bundler.js:5458
patch @ runtime-core.esm-bundler.js:5094
mountChildren @ runtime-core.esm-bundler.js:5285
mountElement @ runtime-core.esm-bundler.js:5195
processElement @ runtime-core.esm-bundler.js:5178
patch @ runtime-core.esm-bundler.js:5098
mountChildren @ runtime-core.esm-bundler.js:5285
mountElement @ runtime-core.esm-bundler.js:5195
processElement @ runtime-core.esm-bundler.js:5178
patch @ runtime-core.esm-bundler.js:5098
mountChildren @ runtime-core.esm-bundler.js:5285
mountElement @ runtime-core.esm-bundler.js:5195
processElement @ runtime-core.esm-bundler.js:5178
patch @ runtime-core.esm-bundler.js:5098
mountChildren @ runtime-core.esm-bundler.js:5285
mountElement @ runtime-core.esm-bundler.js:5195
processElement @ runtime-core.esm-bundler.js:5178
patch @ runtime-core.esm-bundler.js:5098
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
(anonymous) @ runtime-core.esm-bundler.js:1487
Promise.then (async)
registerDep @ runtime-core.esm-bundler.js:1466
mountComponent @ runtime-core.esm-bundler.js:5532
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
mountChildren @ runtime-core.esm-bundler.js:5285
processFragment @ runtime-core.esm-bundler.js:5458
patch @ runtime-core.esm-bundler.js:5094
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
componentUpdateFn @ runtime-core.esm-bundler.js:5638
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
setupRenderEffect @ runtime-core.esm-bundler.js:5759
mountComponent @ runtime-core.esm-bundler.js:5541
processComponent @ runtime-core.esm-bundler.js:5499
patch @ runtime-core.esm-bundler.js:5101
patchBlockChildren @ runtime-core.esm-bundler.js:5406
processFragment @ runtime-core.esm-bundler.js:5469
patch @ runtime-core.esm-bundler.js:5094
componentUpdateFn @ runtime-core.esm-bundler.js:5711
run @ reactivity.esm-bundler.js:187
instance.update @ runtime-core.esm-bundler.js:5745
callWithErrorHandling @ runtime-core.esm-bundler.js:157
flushJobs @ runtime-core.esm-bundler.js:390
Promise.then (async)
queueFlush @ runtime-core.esm-bundler.js:282
queueJob @ runtime-core.esm-bundler.js:276
scheduler @ runtime-core.esm-bundler.js:1827
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:387
triggerRefValue @ reactivity.esm-bundler.js:1003
(anonymous) @ reactivity.esm-bundler.js:1137
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:1003
(anonymous) @ reactivity.esm-bundler.js:1137
triggerEffect @ reactivity.esm-bundler.js:397
triggerEffects @ reactivity.esm-bundler.js:382
triggerRefValue @ reactivity.esm-bundler.js:1003
set value @ reactivity.esm-bundler.js:1048
signout @ users.ts:100
await in signout (async)
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
emit$1 @ runtime-core.esm-bundler.js:714
(anonymous) @ runtime-core.esm-bundler.js:7430
handleClick @ DropdownItem.vue:22
callWithErrorHandling @ runtime-core.esm-bundler.js:157
callWithAsyncErrorHandling @ runtime-core.esm-bundler.js:166
invoker @ runtime-dom.esm-bundler.js:345
```
</details>

![imagen](https://user-images.githubusercontent.com/6311119/206923622-da26bfe9-9c77-4258-9585-507e744f3f92.png)

**Comment by boehs** [comment]
Does this still happen? Seems like this could be stale

**Comment by userquin** [comment]
@boehs I reproduce it on elk.zone every time I sign-out, also on private browsing. I talk with Daniel and seems to be a bug, we still have som race condition.

**Comment by userquin** [comment]
@boehs forgot it, this can be closed, seems to be not related with this another one: https://github.com/elk-zone/elk/issues/1621
